// This is an independent project of an individual developer. Dear PVS-Studio, please check it.
// PVS-Studio Static Code Analyzer for C, C++, C#, and Java: http://www.viva64.com
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "pch.h"
#include "explorer.h"

/////////////////////////////////////////////////////////////////////////////
// CExplorer

IMPLEMENT_DYNCREATE(CExplorer, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CExplorer properties

/////////////////////////////////////////////////////////////////////////////
// CExplorer operations
