//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VideoCat.rc
//
#define IDOK2                           3
#define ID_BY_GENRE_NAME                3
#define ID_DELETE_TAG                   3
#define IDC_CLEAR_TAGS                  3
#define IDD_ABOUTBOX                    100
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDS_START_YOUR_WORK             129
#define IDR_VideoCatTYPE                130
#define IDS_ADD_ROOT                    130
#define IDS_MOVE_ROOT                   131
#define IDS_DELETE_ROOT                 132
#define IDS_OPEN_FOLDER                 133
#define IDS_SYNCHRONIZE                 134
#define IDS_AUTOFILL                    135
#define IDS_UPDATE_THUMBNAILS           136
#define IDS_STATISTICS                  137
#define IDS_STATISTICS_GENRE            138
#define IDS_STATISTIC_YEAR              139
#define IDS_EXPORT_EXCEL                140
#define IDS_RANDOM                      141
#define IDS_SETTINGS                    142
#define IDS_FEEDBACK                    143
#define IDS_ABOUT                       144
#define IDS_SORT_BY_YEAR_DOWN           145
#define IDS_SORT_BY_YEAR_UP             146
#define IDS_SORT_BY_RUSSIAN_NAME        147
#define IDS_SORT_BY_ORIGINAL_NAME       148
#define IDS_SITE_FORUM                  149
#define IDS_TASK_REMOVE_ROOT_BTN        150
#define IDS_TASK_REMOVE_ROOT_CANCEL_BTN 151
#define IDS_TASK_REMOVE_ROOT_MSG        152
#define IDS_TASK_REMOVE_ROOT_HEADER     153
#define IDS_TASK_REMOVE_ROOT_TITLE      154
#define IDS_TASK_REMOVE_ROOT_INFO       155
#define IDS_ERROR                       156
#define IDS_ERROR_SYNCHRONIZE_NOT_FINISHED 157
#define IDS_ERROR_ROOT_NOT_FOUNDED      158
#define IDS_NO_NEW_FILMS                159
#define IDS_TASK_SYNCHRONIZE_MESSAGE    160
#define IDS_TASK_SYNCHRONIZE_TITLE      161
#define IDS_TASK_SYNCHRONIZE_INFO       162
#define IDS_TASK_SYNCHRONIZE_OK         163
#define IDS_TASK_SYNCHRONIZE_CANCEL     164
#define IDS_TASK_BING_MSG               165
#define IDS_SETTINGS_STYLE              165
#define IDS_TASK_BING_HEADER            166
#define IDS_IMPORT_FROM_ARCHIVID        166
#define IDS_TASK_BING_TITLE             167
#define IDS_SHOW_NEW_FILMS              167
#define IDS_TASK_BING_INFO              168
#define IDS_FILE_TITLE_NEW_FILMS        168
#define IDS_FILTER_TITLE_NEW_FILMS      168
#define IDS_TASK_BING_LEARN_MORE        169
#define IDS_SORT_BY_DATE                169
#define IDS_TASK_BING_CONTINUE          170
#define IDS_EXPORT_ANDROID              170
#define IDS_BING_HELP                   171
#define IDS_EXPORT_COLLECTION           171
#define IDS_PROGRESS_SEARCH_POSTERS     172
#define IDS_PROGRESS_DOWNLOAD_POSTERS   173
#define IDS_PROGRESS_FILL_CARDS         174
#define IDS_PROGRESS_AUTOFILL_STATISTIC 175
#define IDS_LOST_FILE                   176
#define IDS_TASK_THUMBS_MSG             177
#define IDS_TASK_THUMBS_HEADER          178
#define IDS_TASK_THUMBS_TITLE           179
#define IDS_TASK_THUMBS_INFO            180
#define IDS_TASK_THUMBS_ONLY_NEW        181
#define IDS_TASK_THUMBS_ALL             182
#define IDS_TASK_THUMBS_DISALLOW        183
#define IDS_PLAY                        184
#define IDS_MENU                        185
#define IDS_YOUTUBE                     185
#define IDS_SITE_FEEDBACK               186
#define IDS_FILM_EDIT                   187
#define IDS_FILM_SHARE                  188
#define IDS_FILM_WEBPAGE                189
#define IDS_FILM_UPDATE_THUMB           190
#define IDS_EDIT_TOOLBAR                190
#define IDS_NUM_PLAYS                   191
#define IDS_RENAME_FILE                 191
#define IDS_TASK_PLAY_HEADER            192
#define IDS_ERROR_TASK_PLAY_TITLE       193
#define IDS_TASK_PLAY_INFO              194
#define IDS_NUM_PLAYS_2                 195
#define IDS_RENAME_FILES                195
#define IDS_ERROR_USE_MANUAL_REMOVE     196
#define IDS_ERROR_LOST_CONVERTER        197
#define IDS_FILTER_TITLE_RANDOM         198
#define IDS_FILTER_TITLE_NAME           199
#define IDS_FILTER_TITLE_YEAR           200
#define IDS_FILTER_TITLE_GENRE          201
#define IDS_VK_INFO_MESSAGE             202
#define IDS_VK_FAILED                   203
#define IDS_ERROR_SHORTCUT_ERROR        204
#define IDS_SETTINGS_SHORTCUT           205
#define IDS_SETTINGS_FORMATS            206
#define IDS_SETTINGS_BING               207
#define IDS_SETTINGS_PROXY              207
#define IDS_MAINFRAME_TITLE             208
#define IDS_TAG                         209
#define IDS_TAG_EDIT                    209
#define IDS_FILTER_TITLE_TAG            210
#define IDS_ERASE_FOLDER                211
#define IDS_SETTINGS_BEHAVIOR           212
#define IDS_STATISTICS_DUPLICATES       213
#define IDS_NO_DUPLICATES               214
#define IDS_READ_FILE_INFO              215
#define IDS_FILTER_TITLE_RECENTLY       216
#define IDS_AUTOFILL_SERIES             217
#define IDS_SIMILAR_FILMS               218
#define IDS_SEARCH_TAG                  219
#define IDS_SCREENSHOT                  220
#define IDS_FOLDER_PROPS                221
#define IDS_ROOT_ACTOR                  222
#define IDS_SORT_BY_FILENAME_UP         222
#define IDS_ROOT_PRODUCER               223
#define IDS_SORT_BY_FILENAME_DOWN       223
#define IDS_SORT                        224
#define IDS_LAST_VIEWED                 225
#define IDS_ADD_PERSON                  226
#define IDS_REMOVE_PERSON               227
#define IDS_UPDATE_PERSON               228
#define IDS_DEFAULT_DB_NAME             229
#define IDS_COLLECTION                  230
#define IDS_ADD_COLLECTION              231
#define IDS_DELETE_COLLECTION           232
#define IDS_EDIT_COLLECTION             233
#define IDS_COLLECTION_NOT_FOUND        234
#define IDS_ERROR_COLLECTION_FORMAT_ERROR 235
#define IDS_ERROR_COLLECTION_SAVE_ERROR 236
#define IDS_CONVERT_OLD_COLLECTION      237
#define IDS_COMMENT_ROOT                237
#define IDS_ROOT_DIRECTORY              238
#define IDS_ADD_FOLDER                  239
#define IDS_ADD_FILM                    240
#define IDS_REMOVE_FOLDER               241
#define IDS_REMOVE_FILM                 242
#define IDS_LOCK_FOLDER                 243
#define IDS_UNLOCK_FOLDER               244
#define IDS_FREE_LIMIT_PERSONS          245
#define IDS_COMMENT_SHAREWARE           245
#define IDS_FREE_LIMIT_ENTRIES          246
#define IDS_LICENSE_TYPE_4              246
#define IDS_SORT_BY_DEFAULT             247
#define IDS_COMMENT_ROOT_REAL           248
#define IDS_COMMENT_ROOT_VIRTUAL        249
#define IDS_COMMENT_DELETE_ROOT         250
#define IDS_COMMENT_RENAME_ROOT         251
#define IDS_YOUTUBE_SEARCH_REVIEW       252
#define IDS_YOUTUBE_SEARCH_REVIEW_YEAR  253
#define IDS_SORT_GLOBAL_BY_YEAR_DOWN    254
#define IDS_SORT_GLOBAL_BY_YEAR_UP      255
#define IDS_SORT_GLOBAL_BY_RUSSIAN_NAME 256
#define IDS_SORT_GLOBAL_BY_ORIGINAL_NAME 257
#define IDS_SORT_GLOBAL_BY_DATE         258
#define IDS_SORT_GLOBAL_BY_FILENAME_UP  259
#define IDS_SORT_GLOBAL_BY_FILENAME_DOWN 260
#define IDS_FIRST_RUN                   261
#define IDS_COMMENT_COPY_FOLDER         262
#define IDS_COPY_FROM_FOLDER            263
#define IDS_NO_NEW_VERSION              264
#define IDS_NEW_VERSION_FOUNDED         265
#define IDS_LICENSE_USERNAME            266
#define IDS_LICENSE_EMAIL               267
#define IDS_LICENSE_TYPE_1              268
#define IDS_LICENSE_TYPE_2              269
#define IDS_LICENSE_TYPE_3              270
#define IDS_UNREGISTERED_VERSION        271
#define IDS_COMMENT_ADD_COLLECTION      272
#define IDS_ERROR_NO_COLLECTION_TITLE   273
#define IDS_ERROR_NO_COLLECTION_FILENAME 274
#define IDS_ERROR_NO_IMAGE_URL          275
#define IDS_ERROR_NO_IMAGE_PATH         276
#define IDS_CONFIRM_DELETE_FILM         277
#define IDS_CONFIRM_DELETE_FOLDER       278
#define IDS_CONFIRM_DELETE_PERSON       279
#define IDS_CONFIRM_RENAME_FILES        280
#define IDS_FILE_RENAME_INFO            281
#define IDS_RENAMING_FILES              282
#define IDS_FILE_FILTER_IMAGES          283
#define IDS_READ_FILE_INFO_PROGRESS     284
#define IDS_NO_FILES_TO_RENAME          285
#define IDS_COMMENT_SET_NEW_COLLECTION_TITLE 286
#define IDS_COMMENT_SET_COLLECTION_DIRECTORY 287
#define IDS_ERROR_EMPTY_COLLECTION_PATH 288
#define IDS_STRING289                   289
#define IDS_OSK_FIND_BY_NAME            289
#define IDS_IRREMOVABLE_EDIT_ERROR      290
#define IDS_CREATE_BACKUP               291
#define IDS_LOAD_BACKUP                 292
#define IDS_COMMENT_CREATE_BACKUP       293
#define IDS_COMMENT_LOAD_BACKUP         294
#define IDS_BACKUP_FILTER               295
#define IDS_SELECT_COLLECTION           296
#define IDS_DONATE                      297
#define IDS_EDIT_MENU                   306
#define IDD_VIDEOTREEVIEW               310
#define IDB_BITMAP1                     315
#define IDD_PROGRESS                    321
#define IDD_FILE_SETTINGS               322
#define IDD_TAB_FILM_INFO               322
#define IDB_ABOUT                       327
#define IDB_MAIN                        328
#define IDB_FILTER                      329
#define IDB_FILM3D                      331
#define IDD_FILE_FORMATS                332
#define IDD_EXTENSION_TYPE              334
#define IDD_SHORTCUT                    338
#define IDB_BITMAP2                     340
#define IDD_GENRE                       341
#define IDB_BG_DESCRIPTION              348
#define IDB_EYES                        353
#define IDB_BITMAP3                     357
#define IDB_CLEAR                       357
#define IDR_TEXT1                       361
#define IDR_CHART_TEMPLATE              361
#define IDD_DIALOG1                     364
#define IDD_SETTINGS                    364
#define IDD_WAIT                        374
#define IDB_EDIT                        379
#define IDD_TAB_DESCRIPTION             380
#define IDB_LOGO                        406
#define IDB_RATING                      408
#define IDB_GOBACK                      409
#define IDB_FOLDER                      410
#define IDB_PNG1                        412
#define IDB_10                          412
#define IDI_ICON1                       414
#define IDI_LOK                         419
#define IDI_ICON2                       420
#define IDD_ERASE                       422
#define IDB_PNG2                        424
#define IDB_BITMAP5                     426
#define IDD_BEHAVIOR                    427
#define IDD_DUBLICATES                  429
#define IDB_PNG3                        434
#define IDI_ICON3                       435
#define IDD_READ_FILE_INFO              437
#define IDD_TAB_TECH_INFO               437
#define IDB_SERIAL_LOGO                 444
#define IDD_SERIAL_FILL                 445
#define IDB_BITMAP4                     449
#define IDB_SAD                         451
#define IDD_PROGRAM_ERROR               452
#define IDB_PERSONS                     457
#define IDB_DIRECTORIES                 458
#define IDD_EDIT_PERSON                 464
#define IDB_BITMAP6                     467
#define IDB_HELP                        467
#define IDB_BITMAP7                     468
#define IDB_PERSON                      468
#define IDI_ADD_COLLLECTION             474
#define IDB_PNG4                        483
#define IDB_BUTTONS                     483
#define IDB_PLUS                        485
#define IDB_MINUS                       486
#define IDB_SAVE                        487
#define IDB_TAG                         488
#define IDD_TEST_PASSWORD               492
#define IDD_EXCLUDED_FILES              494
#define IDD_SYNCHRONIZE                 497
#define IDD_PROXY_SETTINGS              498
#define IDB_PROXY                       500
#define IDB_FOLDER_LOCKED               504
#define IDB_FOLDER_VIRTUAL              505
#define IDB_LOCK                        508
#define IDD_PRIVATE_LOCK                509
#define IDB_FILE                        511
#define IDB_URL                         512
#define IDB_FILE_TREE                   513
#define IDD_EDIT_CARD                   514
#define IDD_TAB_AUTOFILL                516
#define IDD_TAB_POSTER                  517
#define IDB_ARROW_LR                    519
#define IDB_FIND                        523
#define IDD_SELECT_AUTOFILL_PLUGIN      524
#define IDB_PLUGIN_BIG                  526
#define IDB_EDIT_CARD_BG                527
#define IDD_STARTUP_HINTS               528
#define IDD_TIP_OF_DAY                  528
#define IDB_ROOT_CAT                    530
#define IDB_SETTING_CAT                 531
#define IDD_DIALOG2                     532
#define IDD_VIEW_STYLE                  532
#define IDD_ARCHIVID                    535
#define IDD_ANDROID                     541
#define IDB_ANDROID_QR                  544
#define IDD_DIALOG3                     545
#define IDD_CHECK_LIST                  545
#define IDB_VIEW_SETTINGS_16            547
#define IDD_RENAME                      551
#define IDB_DOWN                        554
#define IDB_UP                          555
#define IDI_FILE_DOWN                   556
#define IDD_COPY_PAGE                   558
#define IDB_SHADOW                      563
#define IDI_ICON5                       565
#define IDD_THEME_EDIT                  566
#define IDD_THEME_BG                    569
#define IDD_THEME_TILE                  572
#define IDD_THEME_SHADOW                575
#define IDD_THEME_LIST                  576
#define IDD_THEME_TREE                  577
#define IDD_THEME_MENU                  578
#define IDB_TREE_ICON                   579
#define IDB_TREE_ICONS                  579
#define IDB_ICON_MAP                    581
#define IDB_PNG5                        583
#define IDB_STARS                       583
#define IDD_DIALOG4                     584
#define IDD_THEME_NAME                  584
#define IDB_NOPOSTER                    586
#define IDB_NOPOSTER_SMALL              587
#define IDB_PNG6                        588
#define IDB_EPISODE_SMALL               588
#define IDD_MANAGE_COLLECTION           589
#define IDD_DIALOG5                     595
#define IDD_CREATE_COLLECTION           595
#define IDD_ADD_COLLECTION              596
#define IDD_CREATE_ROOT_DIRECTORY       597
#define IDD_EDIT_REAL_ROOT              599
#define IDD_MANAGE_ROOT_DIRECTORY       602
#define IDD_DELETE_ROOT                 605
#define IDD_ROOT_TITLE                  607
#define IDD_EDIT_TOOLBAR                610
#define IDD_THUMBNAIL_SETTINGS          613
#define IDD_FIRST_RUN                   615
#define IDD_COPY_FOLDER_DATA            616
#define IDI_FOLDER_ICON                 620
#define IDI_DATABASE                    621
#define IDB_KEYBOARD                    622
#define IDD_ONSCREEN_KEYBOARD           623
#define IDB_COLOR_THEME                 625
#define IDB_SHAREWARE                   629
#define IDD_MAINTENANCE                 630
#define IDD_CREATE_BACKUP               632
#define IDD_LOAD_BACKUP                 635
#define IDD_DIALOG6                     639
#define IDD_CAMERA_DIALOG               639
#define IDC_FIND_BY_NAME                1000
#define IDC_ROOT_TREE                   1001
#define IDC_BTN_ADD_ROOT                1002
#define IDC_BTN_MAIN                    1002
#define IDC_BTN_ABOUT                   1003
#define IDC_ROOT_TREE_LIST              1003
#define IDC_BTN_OPEN_FILTER             1004
#define IDC_PROGRESS                    1005
#define IDC_BTN_SETTINGS                1005
#define IDC_BTN_OPEN_FILTER2            1005
#define IDC_BTN_KEYBOARD                1005
#define IDC_PROGRESS_STEPS              1006
#define IDC_PROGRESS_TITLE              1007
#define IDC_OBJECT_NAME                 1008
#define IDC_TITLE_RUSSIAN               1008
#define IDC_OBJECT_PATH                 1009
#define IDC_RADIO_POSTER_1              1010
#define IDC_RADIO_POSTER_2              1011
#define IDC_RADIO_POSTER_3              1012
#define IDC_RADIO_POSTER_4              1013
#define IDC_EDIT_POSTER_URL             1014
#define IDC_POSTER_PATH                 1015
#define IDC_CHECK_3DMOVIE               1016
#define IDC_RADIO_POSTER_6              1016
#define IDC_TITLE_ORIGINAL              1017
#define IDC_TITLE_YEAR                  1018
#define IDC_RADIO_POSTER_5              1019
#define IDC_RADIO_POSTER_7              1019
#define IDC_GENRES                      1020
#define IDC_SEASON                      1021
#define IDC_EPISODE                     1022
#define IDC_AUTORUN_SYNC                1023
#define IDC_LINK                        1024
#define IDC_AUTORUN_THUMBS              1024
#define IDC_LIST_FORMATS                1025
#define IDC_UPDATE_THUMBS               1025
#define IDC_AUTORUN_TECHINFO            1025
#define IDC_BTN_ADD_FORMAT              1026
#define IDC_BTN_REMOVE_FORMAT           1027
#define IDC_RADIO_DEFAULT_PLAYER        1028
#define IDC_RADIO_CUSTOM_PLAYER         1029
#define IDC_PLAYER_PATH                 1030
#define IDC_PLAYER_COMMANDS             1031
#define IDC_3D_INDIVIDUAL               1032
#define IDC_LINK_LEARN                  1033
#define IDC_EXTENSION_NAME              1034
#define IDC_MFCLINK1                    1035
#define IDC_VERSION_BLOCK               1036
#define IDC_PROGRAM_VERSION             1037
#define IDC_SHORTCUT_NAME               1038
#define IDC_PROGRAM_VERSION2            1038
#define IDC_LEARN_MORE                  1039
#define IDC_CREATE_SHORTCUT             1040
#define IDC_ONLY_3D_FILMS               1041
#define IDC_WITHOUT_POSTERS             1043
#define IDC_OPEN_DESCRIPTION            1045
#define IDC_AUTO_FILL                   1046
#define IDC_SAVE                        1051
#define IDC_EXPLORER                    1053
#define IDC_CINEMATE_ID                 1060
#define IDC_FILM_ID                     1060
#define IDC_BTN_ORDER                   1061
#define IDC_BTN_PERSONES                1061
#define IDC_BTN_ORDER2                  1062
#define IDC_BTN_CHART                   1062
#define IDC_BTN_RECENTLY                1062
#define IDC_BTN_DIRECTORIES             1062
#define IDC_STATIC_2                    1063
#define IDC_BTN_PERSONES2               1063
#define IDC_BTN_HELP                    1063
#define IDC_EDIT1                       1064
#define IDC_BTN_VIEW_SETTINGS           1064
#define IDC_LOGO                        1065
#define IDC_EDIT2                       1065
#define IDC_BTN_CLEAR                   1066
#define IDC_EDIT3                       1066
#define IDC_BTN_EDIT_DESCRIPTION        1067
#define IDC_POST_RU                     1067
#define IDC_SHADOW_OPACITY              1067
#define IDC_BUTTON2                     1068
#define IDC_COPY_INFO                   1068
#define IDC_BTN_EDIT_TAG                1068
#define IDC_FILL_BY_NAME                1068
#define IDC_PRE_EN                      1068
#define IDC_CHECK_IP                    1068
#define IDC_MARKER_OPACITY              1068
#define IDC_COPY_FROM_CLIPBOARD         1068
#define IDC_SETTINGS_TAB                1069
#define IDC_POST_EN                     1069
#define ID_CREATE_SHORTCUT              1070
#define IDC_SPLIT1                      1078
#define IDC_CHK_FUZZY_YEAR              1080
#define IDC_EDIT_TAGLINE                1081
#define IDC_EDIT_DESCRITPION            1082
#define IDC_EDIT_TITLE                  1083
#define IDC_EDIT_DESCRITPION2           1083
#define IDC_EDIT_COMMENT                1083
#define IDC_MFCLINK2                    1091
#define IDC_MFCLINK3                    1092
#define IDC_STRICT_GENRE                1094
#define ID_BY_GENRES                    1095
#define IDC_CHECK1                      1096
#define IDC_CHK_INNER_FILMS             1096
#define IDC_DELETE_KINOPOISK            1096
#define IDC_CLOSE_BEFORE_PLAY           1096
#define IDC_DELETE_LOCK                 1096
#define IDC_CHK_AUTOFILL                1096
#define IDC_CHECK_HINTS                 1096
#define IDC_CHECK_FONT                  1096
#define IDC_FILTER_RU                   1096
#define IDC_USE_YEAR                    1096
#define IDC_RENAME_COLLECTION           1096
#define IDC_AUTOSAVE_CHANGES            1096
#define IDC_BACKUP_COLLECTION           1096
#define IDC_DELETE_TAGS                 1097
#define IDC_CHK_INNER_FILMS2            1097
#define IDC_CHK_HIDDEN                  1097
#define IDC_CHK_TECHINFO                1097
#define IDC_FILTER_EN                   1097
#define IDC_DELETE_COMMENTS             1097
#define IDC_USE_RUS                     1097
#define IDC_BACKUP_PROGRESS             1097
#define IDC_TAGS                        1098
#define IDC_DELETE_POSTERS              1098
#define IDC_CHK_THUMBS                  1098
#define IDC_FILTER_YEAR                 1098
#define IDC_USE_EN                      1098
#define IDC_BACKUP_FRAMES               1098
#define IDC_DELETE_THUMBS               1099
#define IDC_FILTER_GENRE                1099
#define IDC_DELETE_COUNTERS             1100
#define IDC_FILTER_TAG                  1100
#define IDC_RADIO_GENRE                 1101
#define IDC_DELETE_TAGS2                1101
#define IDC_DELETE_TECHINFO             1101
#define IDC_FILTER_TREE                 1101
#define IDC_RADIO_TAG                   1102
#define IDC_DELETE_TAGS3                1102
#define IDC_BUTTON1                     1104
#define IDC_BTN_ERASE                   1104
#define IDC_READ_FILE_INFO              1104
#define IDC_BTN_READ_SITE               1104
#define IDC_FILL_BY_ID_DB               1104
#define IDC_BTN_NEXT_HINT               1104
#define IDC_BTN_DELETE                  1104
#define IDC_MOVE_UP                     1104
#define IDC_SAVE_TO_DISK                1104
#define IDC_MARK_NOT_VIEWED             1105
#define IDC_CLEAR_FILE_INFO             1105
#define IDC_BUTTON3                     1105
#define IDC_FILL_BY_ID_SITE             1105
#define IDC_BTN_PREV_HINT               1105
#define IDC_MOVE_DOWN                   1105
#define IDC_MOVE_UP2                    1105
#define IDC_MARK_VIEWED                 1106
#define IDC_MARK_NONE                   1107
#define IDC_VIEW_TILES                  1108
#define IDC_VIEW_LIST_SERIES            1109
#define IDC_MFCPROPERTYGRID             1109
#define IDC_VIEW_SERIES                 1110
#define IDC_VIEW_LIST                   1110
#define IDC_CHECK2                      1111
#define IDC_BIG_PREVIEW                 1111
#define IDC_CHK_SHOW_RATINGS            1111
#define IDC_CHANGE_PRIVATE              1111
#define IDC_EXPORT_DESCRIPTION          1111
#define IDC_ERASE_FOLDER                1111
#define IDC_LIST                        1112
#define IDC_BG_FILE                     1113
#define IDC_BG_CLEAR                    1114
#define IDC_LIGHT_THEME                 1115
#define IDC_RADIO2                      1116
#define IDC_DARK_THEME                  1116
#define IDC_RADIO1                      1116
#define IDC_TYPE_SHARED                 1116
#define IDC_RADIO_FILL_SKIP             1116
#define IDC_RADIO_PLUGIN                1116
#define IDC_EXPORT_ALL                  1116
#define IDC_NO_PROXY                    1116
#define IDC_BG_IMAGE                    1116
#define IDC_CREATE_NEW                  1116
#define IDC_TYPE_LOCAL                  1117
#define IDC_ERROR_TEXT                  1117
#define IDC_RADIO3                      1117
#define IDC_RADIO_FILL_USER             1117
#define IDC_RADIO_MANUAL                1117
#define IDC_BG_CLEAR2                   1117
#define IDC_COLORS_CLEAR                1117
#define IDC_EXPORT_SELECTED             1117
#define IDC_USE_TOR                     1117
#define IDC_BG_GRADIENT                 1117
#define IDC_CREATE_ALL                  1117
#define IDC_LIST1                       1118
#define IDC_USED_TAGS                   1118
#define IDC_ALL_EXCLUDED_FOLDERS        1118
#define IDC_LICENSE_INFO                1118
#define IDC_RADIO_FILL_AUTO             1118
#define IDC_EXPORT_NOT_SELECTED         1118
#define IDC_CHECK_LIST                  1118
#define IDC_EXAMPLE                     1118
#define IDC_USE_PROXY                   1118
#define IDC_THEME_LIST                  1118
#define IDC_COLLECTION_LIST             1118
#define IDC_COMMAND_LIST                1118
#define IDC_STAGE                       1118
#define IDC_LIST2                       1119
#define IDC_ALL_TAGS                    1119
#define IDC_FILM_LIST                   1119
#define IDC_ORDER                       1119
#define IDC_TOOLBAR_LIST                1119
#define IDC_COMBO1                      1120
#define IDC_DATABASE_LIST               1120
#define IDC_COMBO_PLUGIN                1120
#define IDC_FILL_PLUGIN                 1120
#define IDC_PLUGIN                      1120
#define IDC_TITLE                       1121
#define IDC_ROOT_LIST                   1121
#define IDC_RADIO7                      1121
#define IDC_EDIT_URL                    1122
#define IDC_EDIT_NAME_RU                1123
#define IDC_COLLECTION_FOLDER           1124
#define IDC_LOAD_COLLECTION             1125
#define IDC_COLLECTION_TITLE            1126
#define IDC_DELETE_COLLECTION           1127
#define IDC_URL                         1131
#define IDC_BTN_NEW_TAG                 1134
#define IDC_BTN_DELETE_TAG              1135
#define IDC_NEW_TAG_NAME                1136
#define IDC_BTN_NEW_TAG2                1137
#define IDC_BTN_RENAME_TAG              1137
#define IDC_EDIT_RATING                 1139
#define IDC_PASSWORD                    1143
#define IDC_EXCLUDED_FOLDER             1145
#define IDC_ADD_EXLUDED                 1146
#define IDC_REMOVE_EXCLUDED             1147
#define IDC_NEW_FILMS                   1148
#define IDC_LOST_FILMS                  1149
#define IDC_FILE_TREE                   1150
#define IDC_MAXIMIZE                    1151
#define IDC_HIDE_SECOND_TITLE           1152
#define IDC_TAB_RECT                    1153
#define IDC_HIDE_SECOND_TITLE2          1153
#define IDC_SHOW_TIP_OF_DAY             1153
#define IDC_DATETIMEPICKER1             1154
#define IDC_DATE                        1154
#define IDC_MFCBUTTON1                  1155
#define IDC_LOAD_POSTER                 1155
#define IDC_APLY_FILM                   1155
#define IDC_APPLY_FILM                  1155
#define IDC_SELECT_TAGS                 1155
#define IDC_BTN_UP                      1155
#define IDC_VK_SUBSCRIBE                1155
#define IDC_EDIT_BG                     1155
#define IDC_CREATE_REAL_ROOT            1155
#define IDC_CREATE_ROOT_BTN             1155
#define IDC_NUM_VIEWS                   1156
#define IDC_BTN_DOWN                    1156
#define IDC_VK_SUBSCRIBE2               1156
#define IDC_BUY                         1156
#define IDC_EDIT_TILE                   1156
#define IDC_CREATE_VIRTUAL_ROOT         1156
#define IDC_MFCBUTTON3                  1156
#define IDC_DELETE_ROOT_BTN             1156
#define IDC_POSTER_IMG                  1157
#define IDC_EDIT_LIST                   1157
#define IDC_RENAME_ROOT_BTN             1157
#define IDC_EDIT_ROOT_BTN               1157
#define IDC_FILM_TITLE                  1158
#define IDC_EDIT_TREE                   1158
#define IDC_EXCLUDE_FOLDER_BTN          1158
#define IDC_RU_LIGHT                    1159
#define IDC_EDIT_MENU                   1159
#define IDC_RU_DARK                     1160
#define IDC_MFCBUTTON7                  1160
#define IDC_EN_LIGHT                    1161
#define IDC_SAVE_AS                     1161
#define IDC_EN_DARK                     1162
#define IDC_EDIT_SHADOW                 1162
#define IDC_FONT                        1163
#define IDC_ARCHIVID_DIR                1164
#define IDC_COLLECTION_NAME             1165
#define IDC_CHECK3                      1166
#define IDC_ANALYTICS                   1166
#define IDC_AUTOPLAY_RANDOM             1166
#define IDC_EXPORT_PATH                 1167
#define IDC_EXPORT_THEME                1168
#define IDC_INFO                        1169
#define IDC_INFO_VALUES                 1170
#define IDC_PRE_YEAR                    1170
#define IDC_POST_YEAR                   1171
#define IDC_PRE_RU                      1172
#define IDC_PRE_EPISODE                 1173
#define IDC_IP_ADDRESS                  1173
#define IDC_POST_EPISODE                1174
#define IDC_IP_PORT                     1174
#define IDC_TIMEOUT                     1175
#define IDC_EXPLORER1                   1176
#define IDC_EXPLORER_TEST               1176
#define IDC_MFCBUTTON2                  1177
#define IDC_TUTORIAL                    1177
#define IDC_THEME_PREVIEW               1177
#define IDC_DELETE_BG                   1177
#define IDC_CREATE_COLLECTION           1177
#define IDC_INSTALL_UPDATE              1177
#define IDC_COPY_WEBCAM                 1177
#define IDC_MFCEDITBROWSE1              1178
#define IDC_IMAGE_PATH                  1178
#define IDC_EDIT_COLLECTION             1178
#define IDC_ROOT_PATH                   1178
#define IDC_BACKUP_PATH                 1178
#define IDC_BACKUP_FILE                 1178
#define IDC_MFCCOLORBUTTON1             1179
#define IDC_ADD_COLLECTION              1179
#define IDC_EXTRACT_PATH                1179
#define IDC_MFCCOLORBUTTON2             1180
#define IDC_MFCBUTTON5                  1180
#define IDC_REMOVE_COLLECTION           1180
#define IDC_MFCCOLORBUTTON3             1181
#define IDC_MAINTENANCE                 1181
#define IDC_MFCCOLORBUTTON4             1182
#define IDC_MAINTENANCE2                1182
#define IDC_BACKUP                      1182
#define IDC_SPIN1                       1183
#define IDC_MFCCOLORBUTTON5             1183
#define IDC_SCROLLBAR1                  1184
#define IDC_MFCCOLORBUTTON6             1184
#define IDC_SPIN2                       1185
#define IDC_MFCCOLORBUTTON7             1185
#define IDC_SHADOW_COLOR                1185
#define IDC_SPIN3                       1186
#define IDC_MFCCOLORBUTTON8             1186
#define IDC_MARKER_COLOR                1186
#define IDC_MFCFONTCOMBO1               1188
#define IDC_MFCFONTCOMBO2               1189
#define IDC_EDIT_THEME                  1189
#define IDC_TOP_COLOR                   1190
#define IDC_CREATE_THEME                1190
#define IDC_BOTTOM_COLOR                1191
#define IDC_DELETE_THEME                1191
#define IDC_BORDER_COLOR                1192
#define IDC_CREATE_THEME2               1192
#define IDC_APPLY_THEME                 1192
#define IDC_BORDER_OPACITY              1193
#define IDC_GLASS_COLOR                 1194
#define IDC_GLASS_OPACITY               1195
#define IDC_GLASS_BLUR                  1196
#define IDC_SHADOW_1                    1197
#define IDC_BG_GROUP                    1198
#define IDC_TILE_GROUP                  1199
#define IDC_BUTTON_COLOR                1201
#define IDC_HOVER_COLOR                 1202
#define IDC_SIZE_LINE_1                 1205
#define IDC_SIZE_LINE_2                 1206
#define IDC_COLOR_LINE_1                1207
#define IDC_COLOR_LINE_2                1208
#define IDC_SELECTED_COLOR_LINE_1       1209
#define IDC_SELECTED_COLOR_LINE_2       1210
#define IDC_LIST_GROUP                  1211
#define IDC_SELECTED_BUTTON_COLOR       1211
#define IDC_COLOR_TAG                   1212
#define IDC_SELECTED_BUTTON_HOVER_COLOR 1212
#define IDC_SELECTED_COLOR_TAG          1213
#define IDC_COLOR_GENRE                 1214
#define IDC_SELECTED_COLOR_GENRE        1215
#define IDC_BUTTON_HOVER_COLOR          1216
#define IDC_SIZE_LINE_4                 1217
#define IDC_SIZE_TAG                    1217
#define IDC_MENU_GROUP                  1217
#define IDC_SELECTED_BUTTON_COLOR2      1218
#define IDC_SIZE_GENRE                  1218
#define IDC_TREE_GROUP                  1218
#define IDC_SELECTED_BUTTON_HOVER_COLOR2 1219
#define IDC_DELETE_FONT                 1219
#define IDC_TEXT_SIZE                   1220
#define IDC_COLOR                       1221
#define IDC_SELECTED_COLOR              1222
#define IDC_SIZE_ICON                   1223
#define IDC_SPIN4                       1224
#define IDC_THEME_NAME                  1225
#define IDC_NUM_RANDOM_FILMS            1226
#define IDC_COMMENT                     1227
#define IDC_COMMENT_BOX                 1228
#define IDC_MFCMENUBUTTON1              1229
#define IDC_IMPORT_EXPORT               1229
#define IDC_COPY                        1230
#define IDC_GROUP_CREATE                1232
#define IDC_GROUP_SIZE                  1233
#define IDC_720P                        1234
#define IDC_480P                        1235
#define IDC_270P                        1236
#define IDC_AUTO_FRAMES                 1237
#define IDC_MANUAL_FRAMES               1238
#define IDC_GROUP_FRAME                 1239
#define IDC_720P2                       1240
#define IDC_FULLSIZE                    1240
#define IDC_COPY_DESCROPTION            1241
#define IDC_COPY_POSTER                 1242
#define IDC_COPY_TAGS                   1243
#define IDC_COPY_COMMENT                1244
#define IDC_OSK_STATIC                  1247
#define IDC_SLIDER_SCALE                1249
#define IDC_EDIT_SCALE                  1250
#define IDC_ADD                         1251
#define IDC_REMOVE                      1252
#define IDC_FILTER_1                    1300
#define IDC_WEBCAM_FILTER_1             1300
#define IDC_FILTER_2                    1301
#define IDC_WEBCAM_FILTER_2             1301
#define IDC_FILTER_3                    1302
#define IDC_WEBCAM_FILTER_3             1302

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        641
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1253
#define _APS_NEXT_SYMED_VALUE           311
#endif
#endif
